### ISSUE TITLE
Enquiry component sits in right column when using in-page nav

### ISSUE THREAD

**Issue by foleye** [unimelb/unimelb-design-system#289]
![screen shot 2015-07-16 at 3 03 34 pm](https://cloud.githubusercontent.com/assets/11880447/8723443/edcf533a-2c10-11e5-9257-f637fe76bedd.png)
Would prefer full width in keeping with footer.

**Comment by axelboc** [comment]
From chris.tan on Slack:
> Also if i stick an enquiry form (via the component markup), when you expand the form, the lovely inset disappears and the navigation on the left “hops/skips” down to the bottom of the page (eg. not scrolling aside the form)

**Comment by tannyboy** [comment]
^
Also noticed with any accordions too (probably on inpage tabs too).

If they are left open, you then scroll down to the bottom the "hopping" occurs. if you've resized and closed the tabs - the jump nav overlaps into the footer. like so

![screen shot 2015-10-26 at 10 59 11 am](https://cloud.githubusercontent.com/assets/1499041/10718872/a4226848-7bd0-11e5-87a6-33b86b92417d.png)

This is fixed by resizing the browser as it seems like there is a recalculation of height on resize. In further investigation there is the function initCalcs() that needs to be fired off again.

Would it be possible to fire the initCalcs() func on button click as currently the initCalcs is fired only on first load and resize? [line 51 - jumpnav.js]

**Comment by waitingallday** [comment]
Oh yeah that would make sense, will look into this.

**Comment by yevek** [comment]
Closing this as has been fixed.
