### ISSUE TITLE
seeking image gallery rollover to display larger image and further information

### ISSUE THREAD

**Issue by gyounger** [unimelb/unimelb-design-system#671]
Hi, I've been asked to replicate this sites functionality as much as possible, for a similar project at unimelb:
http://www.teachinghistory100.org
(the key feature being objects in an image gallery, that can be filtered, and display further info on rollover) 

In terms of MCE components, it could be seen to be a combo of the gallery, filtered listing and listing. 

For now I've created the site as a listing, with new items appearing under the objects page when added: 
https://cms.unimelb.edu.au/controlled-environment/tuc

Seeking advice for existing options and or modifications of existing components. 

thanks
Gav

**Comment by yevek** [comment]
Website is now here: http://library.unimelb.edu.au/teachingobjects 

Current page is using an asset listing - but looks a bit funny due to images being different sizes (this is addressed in #709) 

![listing-page](https://cloud.githubusercontent.com/assets/1305804/22007213/26229204-dcc5-11e6-8eb2-e6d90b269835.png)

Gavin is requesting an option to have a rollover version where additional info is displayed via rollover first, then onclick goes to page.

1. http://www.teachinghistory100.org
![images](https://cloud.githubusercontent.com/assets/1305804/22007363/460515c8-dcc6-11e6-9e94-8575142692d0.png)

2. rollover image
![rollover](https://cloud.githubusercontent.com/assets/1305804/22007369/4df73504-dcc6-11e6-92ba-206c5a54b380.png)

3. on click go to page
http://www.teachinghistory100.org/objects/photograph_of_amy_barbour_james

I think this solution is quite elegant - not sure how much work is involved to add as enhancement.

**Comment by axelboc** [comment]
Showing content on hover is out of the question, as mobile users wouldn't be able to see it (amongst other reasons), but would showing the caption on the image itself work?

<img width="909" alt="screen shot 2017-02-02 at 3 06 01 pm" src="https://cloud.githubusercontent.com/assets/2936402/22536869/a839d8a6-e959-11e6-8820-986dd1024b34.png">

**Comment by axelboc** [comment]
I've added a class `image-gallery__caption` which can be used to show an image's caption in the gallery listing. See docs once v6 is released for more info.
