### ISSUE TITLE
Accessibility - Breadcrumb navigation

### ISSUE THREAD

**Issue by anormand** [unimelb/unimelb-design-system#786]
#### Expected behaviour
As a screen reader user, I need to know that the list of breadcrumbs is a navigation item, so that I can understand it's purpose.

#### Actual behaviour
The screen reader reads the breadcrumbs as a list.

#### Steps to reproduce
The current code is:
```html
<ol class="page-local-history" itemscope="" itemtype="http://schema.org/BreadcrumbList">
```

NVDA reads it as:
> list with 3 items 
> clickable
> Web.Unimelb 
> visited link

Suggested code:
```html
<ol class="page-local-history" itemscope="" itemtype="http://schema.org/BreadcrumbList" role="navigation" aria-label="breadcrumb">
```

NVDA will read it as:
> breadcrumb navigation landmark list with 3 items 
> Web.Unimelb 
> visited link

**Comment by waitingallday** [comment]
Will definitely include this in the next release!

**Comment by anormand** [comment]
Excellent, we will be deploying this in the next release of ServiceNow

**Comment by axelboc** [comment]
I went a slightly different route: I've used a `nav` element instead of a `div` for `page-header-navigation` (which wraps `page-local-history`). This has a few advantages:

- it makes use of the implicit aria role of `nav`
- it is consistent with your recommendation regarding `page-header-tools`
- `page-header-navigation` is created by the injection script, whereas `page-local-history` is part of the markup people have to write themselves -- so we avoid a breaking change

**Comment by axelboc** [comment]
For reference the new markup is:

```html
<nav class="page-header-navigation" aria-label="breadcrumbs">
  <ol class="page-local-history">...</ol>
</nav>
```
