### ISSUE TITLE
Suggestion: Put "vertical-align: middle;" on <li> within <ul class="feature-listing-3">

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/unimelb-design-system#801]
#### Actual behaviour
When using feature listings (which are often used to display logos), the `<li>` is currently defaulting to vertically aligning to the top.
Often logos are of different sizes, and don't line up nicely - like the bottom right logo in the screenshot below
**Before** screenshot:
![image](https://cloud.githubusercontent.com/assets/15081925/22533499/ad6a7cf2-e942-11e6-9ab6-df07c9811da3.png)

#### Expected behaviour
Adding `"vertical-align: middle;"` on each `<li>` makes them align vertically relative to each other, which is an improvement.
**After** screenshot:
![image](https://cloud.githubusercontent.com/assets/15081925/22533563/ebc23a08-e942-11e6-96d1-c8cba5ee8dfc.png)

#### Steps to reproduce
See this page as an example - towards bottom of home tab:
http://rirg.fvas.unimelb.edu.au/ag-extension

**Comment by dkevey** [comment]
similar to this one #698

**Comment by waitingallday** [comment]
Just tried this, it won't work as a default value:

![screen shot 2017-02-13 at 3 34 16 pm](https://cloud.githubusercontent.com/assets/863542/22871109/f229b30e-f201-11e6-9722-22b6f6ab56d6.png)

(not sure if it's obvious in the screen above, but the listings are shifted about depending on amount of text)

I'll add a modifier class instead, so that the default can be overridden when needed.
